#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -ea -cp lib/jing.jar:lib/bcm.jar:cps.jar:. -Djava.security.manager \
    -Djava.security.policy=policies/dcvm.policy \
    cps.mouradalpha.DCVMBasic $1 config.xml/config-dcvm_basic.xml