#!/bin/bash
./clean_log
./start-performance-5-broker brokerURI-0&
./start-performance-5-broker brokerURI-1&
./start-performance-5-broker brokerURI-2&
./start-performance-5-broker brokerURI-3&
./start-performance-5-broker brokerURI-4&

