#!/bin/bash
if [ -z "$1" ]; then 
  echo usage: $0 testNumber jvmName
  exit
 fi
java -ea -cp bcm.jar:. -Djava.security.manager \
    -Djava.security.policy=policies/dcvm.policy \
    fr.sorbonne_u.components.examples.basic_cs.DistributedCVM $1 config.xml/config-basic_cs.xml