#!/bin/bash
java -ea -Xms2m -cp bcm.jar:. -Djava.security.manager \
    -Djava.security.policy=policies/dcvm.policy \
    fr.sorbonne_u.components.cvm.utils.DCVMCyclicBarrier\
    config.xml/config-basic_cs.xml
